'use client';

import { useLayoutEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import type { TestResult } from '@/types/personality';
import EnCompatibilityResults from '@/components/en/CompatibilityResults';

export interface SampleCompatibilitySummary {
  score: number;
  description: string;
  tips: string[];
}

export interface SampleAxisInsight {
  label: string;
  verdict: string;
  detail: string;
}

interface EnCompatibilityResultsContainerProps {
  sampleSummary: SampleCompatibilitySummary;
  sampleAxisInsights: SampleAxisInsight[];
  sampleNightParagraphs: string[];
  sampleMyTypeName: string;
  samplePartnerTypeName: string;
}

const EnCompatibilityResultsContainer = ({
  sampleSummary,
  sampleAxisInsights,
  sampleNightParagraphs,
  sampleMyTypeName,
  samplePartnerTypeName,
}: EnCompatibilityResultsContainerProps) => {
  const router = useRouter();
  const [myResult, setMyResult] = useState<TestResult | null>(null);
  const [partnerResult, setPartnerResult] = useState<TestResult | null>(null);
  const [isCheckingResults, setIsCheckingResults] = useState(true);

  useLayoutEffect(() => {
    if (typeof window === 'undefined') {
      setIsCheckingResults(false);
      return;
    }

    try {
      const savedMyResult = window.localStorage.getItem('en_compatibility_my_result');
      const savedPartnerResult = window.localStorage.getItem('en_compatibility_partner_result');

      if (savedMyResult && savedPartnerResult) {
        const parsedMyResult: TestResult = JSON.parse(savedMyResult);
        const parsedPartnerResult: TestResult = JSON.parse(savedPartnerResult);

        setMyResult(parsedMyResult);
        setPartnerResult(parsedPartnerResult);
      }
    } catch (error) {
      console.error('Failed to load compatibility results:', error);
    } finally {
      setIsCheckingResults(false);
    }
  }, []);

  const handleBack = () => {
    router.push('/en/compatibility');
  };

  const handleNewTest = () => {
    if (typeof window !== 'undefined') {
      window.localStorage.removeItem('en_compatibility_my_result');
      window.localStorage.removeItem('en_compatibility_partner_result');
    }
    router.push('/en/compatibility');
  };

  if (myResult && partnerResult) {
    return (
      <EnCompatibilityResults
        myResult={myResult}
        partnerResult={partnerResult}
        onBack={handleBack}
        onNewTest={handleNewTest}
      />
    );
  }

  if (isCheckingResults) {
    return (
      <div className="flex items-center justify-center min-h-screen text-white">
        <div className="text-base text-white/80">Loading...</div>
      </div>
    );
  }

  return (
    <div className="space-y-12">
      <article className="mx-auto w-full max-w-5xl px-4 pb-16 pt-28 space-y-12 text-white">
        <header className="space-y-4">
          <p className="text-sm uppercase tracking-[0.35em] text-white/40">Sample Report</p>
          <h1 className="text-3xl md:text-4xl font-semibold leading-tight">Couple Compatibility Sample Report</h1>
          <p className="text-base md:text-lg text-white/75">
            This page features a digest of the couple report generated by Night Personality Test. In the actual test, a detailed report like the one below is generated instantly based on both partners&apos; answers.
          </p>
        </header>

        <section className="rounded-3xl border border-white/15 bg-white/10 px-6 py-8 md:px-10 md:py-12 backdrop-blur-xl shadow-xl shadow-purple-900/20">
          <div className="space-y-6">
            <div className="flex flex-wrap items-baseline gap-3">
              <span className="inline-flex items-center rounded-full bg-pink-500/20 px-3 py-1 text-xs font-semibold text-pink-200 uppercase tracking-wide">
                Score Overview
              </span>
              <h2 className="text-2xl md:text-3xl font-semibold text-[#fdf4ff]">
                {sampleMyTypeName} x {samplePartnerTypeName}
              </h2>
            </div>

            <div className="grid gap-8 md:grid-cols-[200px,1fr] md:items-center">
              <div className="flex flex-col items-center justify-center rounded-2xl border border-white/10 bg-black/40 p-6 text-center">
                <p className="text-sm uppercase tracking-[0.3em] text-white/40">Compatibility</p>
                <p className="mt-2 text-5xl font-bold text-pink-200">
                  {sampleSummary.score}
                  <span className="text-2xl">%</span>
                </p>
                <p className="mt-2 text-xs text-white/60">Overall Balance Score</p>
              </div>
              <p className="text-base leading-relaxed text-white/80">{sampleSummary.description}</p>
            </div>

            <div className="space-y-3">
              <h3 className="text-lg font-semibold text-white">Improvement Tips (Sample)</h3>
              <ul className="space-y-2 text-sm md:text-base text-white/80">
                {sampleSummary.tips.map((tip) => (
                  <li key={tip} className="flex items-start gap-2">
                    <span className="mt-1 h-2 w-2 flex-shrink-0 rounded-full bg-pink-300" />
                    <span>{tip}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </section>

        <section className="grid gap-6 rounded-3xl border border-white/10 bg-white/5 px-6 py-8 md:px-10 md:py-12 backdrop-blur-lg md:grid-cols-2">
          <div className="space-y-4">
            <h2 className="text-xl font-semibold text-white">Axis Compatibility Highlights</h2>
            <p className="text-sm md:text-base text-white/70">
              The test scores 5 psychological axes to determine similarities and complementary traits. Below are sample highlights.
            </p>
          </div>
          <ul className="space-y-5">
            {sampleAxisInsights.map((insight) => (
              <li key={insight.label} className="rounded-2xl border border-white/5 bg-black/30 p-5">
                <p className="text-sm uppercase tracking-[0.2em] text-white/35">{insight.label}</p>
                <p className="mt-2 text-base font-semibold text-white">{insight.verdict}</p>
                <p className="mt-2 text-sm text-white/70 leading-relaxed">{insight.detail}</p>
              </li>
            ))}
          </ul>
        </section>

        {sampleNightParagraphs.length > 0 && (
          <section className="rounded-3xl border border-pink-500/30 bg-pink-500/10 px-6 py-8 md:px-10 md:py-12 backdrop-blur-lg space-y-4">
            <h2 className="text-xl font-semibold text-pink-50">Intimate Compatibility Insights (Sample)</h2>
            {sampleNightParagraphs.map((paragraph) => (
              <p key={paragraph} className="text-sm md:text-base text-pink-100/90 leading-relaxed">
                {paragraph}
              </p>
            ))}
          </section>
        )}

        <section className="rounded-3xl border border-white/15 bg-gradient-to-br from-[#1f1436] via-[#180d2e] to-[#110722] px-6 py-10 md:px-10 md:py-14 space-y-6">
          <h2 className="text-xl font-semibold text-white">How to Take the Test</h2>
          <p className="text-sm md:text-base text-white/75">
            To see your own report, first complete the personality test and share the QR code displayed on the results page with your partner. Then, scan the code on the compatibility test page to generate your couple report in real time.
          </p>
          <div className="flex flex-wrap gap-3">
            <Link
              href="/en/test"
              className="inline-flex items-center justify-center rounded-full bg-gradient-to-r from-[#6366f1] via-[#8b5cf6] to-[#ec4899] px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-purple-900/30 transition-transform hover:scale-105"
            >
              Take the Personality Test
            </Link>
            <Link
              href="/en/compatibility"
              className="inline-flex items-center justify-center rounded-full border border-white/30 px-6 py-3 text-sm font-semibold text-white/85 transition-transform hover:scale-105 hover:border-white/60"
            >
              View Compatibility Test Steps
            </Link>
          </div>
        </section>
      </article>

      <section className="mx-auto w-full max-w-5xl px-4 pb-24">
        <div className="w-full rounded-3xl border border-white/10 bg-black/30 px-6 py-12 md:px-10 md:py-14 backdrop-blur-lg text-white/85 space-y-6">
          <header className="space-y-3">
            <p className="text-sm uppercase tracking-[0.35em] text-white/50">Guide</p>
            <h2 className="text-2xl md:text-3xl font-semibold">Steps to View Your Couple Report</h2>
            <p className="text-base md:text-lg text-white/70">
              The report above is a sample. To see your actual results, you need to complete two steps: the personality test and the QR code compatibility test.
            </p>
          </header>
          <ol className="list-decimal list-inside space-y-3 text-sm md:text-base text-white/80">
            <li>
              First, take the{' '}
              <Link className="text-pink-300 underline decoration-pink-300" href="/en/test">
                personality test
              </Link>
              {' '}to get your type and test code.
            </li>
            <li>Have your partner take the same test, then scan each other&apos;s QR codes on the compatibility page.</li>
            <li>Once complete, a detailed couple report based on both results will automatically appear on this page.</li>
          </ol>
        </div>
      </section>
    </div>
  );
};

export default EnCompatibilityResultsContainer;
